### ISSUE TITLE
Как быстро поменять порт?

### ISSUE THREAD

**Issue by Zummer** [yarcode/yii2-app-yarcode#18]
Например, я хочу поменять порт у nginx-frontend вместо 8001 установить 8010.
Где это надо изменить, что перезапустить?

**Comment by metalagman** [comment]
в docker-compose.override.yml засунь 
```
services:
  nginx-frontend:
    ports:
      - 8010:8001
```
